apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: banco-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banco
  template:
    metadata:
      labels:
        app: banco
    spec:
      containers:
        - name: banco
          image: moisesalc/banco-it_talent
          ports:
            - containerPort: 5432
